docs/firmware/device-sdk/authentication/guide-auth.md
=> Remove WIP from Auth section

docs/cloud/1-services/4-lightdb-stream/2-sending-data.md, docs/cloud/1-services/4-lightdb-stream/3-querying-data.md, docs/firmware/device-sdk/firmware-upgrade/3-sign-and-flash.md
- Missing new line was breaking
- Rephrased for grammar and readability
=> Fixes: missing newline and readability

docs/hardware/5-virtual-device/1-overview.md
Replace work in progress message with brief overview.
=> Replaced coming soon message with overview info

docs/getting-started/1-console/5-choose-device.md
Applied frontmatter setting per https://docusaurus.io/docs/sidebar/multiple-sidebars#generating-pagination and cleaned up language.
=> Hide next button from quick start

docusaurus.config.js, package-lock.json, package.json, yarn.lock
build: upgrade docusaurus from beta9 to beta15
- move gtag per https://github.com/facebook/docusaurus/pull/5832
=> Upgrade Docusaurus from beta 9 to beta 15

docs/hardware/3-esp32/2-quickstart/5-windows.md, docs/partials/install-espressif-toolchain-windows.md, docs/partials/install-espressif-toolchain.md, docs/partials/install-zephyr-sdk-windows.md, docs/partials/install-zephyr-sdk.md, docs/partials/setup-zephyr-windows.md, docs/partials/setup-zephyr.md
Added instructions for installing toolchain in Windows
* Currently lives an an addendum page but will be incorporated with the Linux/MacOS when we have solved issue with how tabs should be represented for OS choice"
=> Windows toolchain install instructions

docs/hardware/6-catalog/quickstart/xtensa_esp32.md
=> Fix: Change ESP-32 to ESP32

docs/hardware/1-home.md
JIRA: https://golioth.atlassian.net/browse/DSDK-252
Contextual meeting notes: https://docs.google.com/document/d/1LLPXVVRXwRgpBJ6zYaPUDa8O0MsP2unZQrHO6tbdb60/edit#heading=h.kzf0k2dycniy
Update the Hardware overview page to reflect our [internal SDK Device Support page](https://golioth.atlassian.net/wiki/spaces/EN/pages/214401082/SDK+Device+Support) on Confluence.
Signed-off-by: Nick Miller <nick@golioth.io>
=> hardware: refresh overview page with board support tiers

docusaurus.config.js
Add search box in the upper right of docs site.
=> Add algolia search

docs/firmware/zephyr-device-sdk/light-db/README.md
=> firmware: update content format in LightDB State

.env.development, .env.production, docusaurus.config.js, package-lock.json, package.json, yarn.lock
Add PostHog API keys for dev and production to .env.development and .env.production
Add PostHog plugin for docusaurus
=> Add PostHog analytics

docs/firmware/zephyr-device-sdk/authentication/certificate-auth.md
- Update hardcoded credential instructions
- Add section on provisioning
=> firmware: update certificate authentication guide

docs/hardware/4-nrf91/2-zephyr-quickstart/2-set-up-zephyr.md, docs/partials/build-fw-nrf91.md, docs/partials/install-nrf91-sdk-unix.md, docs/partials/install-nrf91-sdk-windows.md, docs/partials/install-nrf91-sdk.md, docs/partials/setup-west-nrf91-windows.md, docs/partials/setup-west-nrf91.md
Fixed Installing the NRF Connect SDK Windows home directory path, added Install West section for Windows
=> hardware, nRF9160

.env.development, .env.production, docs/reference/3-rest-api/1-overview.mdx
Updates docs to include OpenAPI v3 links.
=> feat: add OpenAPI v3 link to docs

.gitpod.yml, README.md
* Use the .editorconf file
* How to install VS Code EditorConfig extension
* Pre-install extensions in GitPod
* Flesh out how to use GitPod section
=> README: add info about styling preferences

docs/firmware/golioth-firmware-sdk/README.md, docs/firmware/golioth-firmware-sdk/golioth-client.md, docs/firmware/zephyr-device-sdk/_category_.yml
* Create new section for the Golioth Firmware SDK
* Document how to use the Golioth Client
=> Firmware SDK: add section and document the Golioth client

docs/cloud/1-services/4-lightdb-stream/2-sending-data.md, docs/firmware/golioth-firmware-sdk/light-db-stream/README.md, docs/firmware/golioth-firmware-sdk/light-db-stream/_category_.yml, docs/firmware/golioth-firmware-sdk/light-db-stream/guide-lightdb-stream-object.md, docs/firmware/golioth-firmware-sdk/light-db-stream/guide-lightdb-stream-type.md
* Firmware-SDK: add LightDB Stream section
* Firmware-SDK: add LightDB Stream by-type
* Firmware-SDK: add LightDB Stream by-object
=> Firmware SDK: add LightDB Stream

package-lock.json, package.json
=> upgrade Docusuarus to 2.4.1

docs/firmware/golioth-firmware-sdk/firmware-upgrade/README.md, docs/firmware/golioth-firmware-sdk/firmware-upgrade/_category_.yml, docs/firmware/golioth-firmware-sdk/firmware-upgrade/dfu-sample-zephyr.md, docs/firmware/golioth-firmware-sdk/firmware-upgrade/guide-ota.md
Add DFU documentation for the Firmware SDK.
=> firmware: dfu: add dfu documentation

docs/cloud/1-services/4-lightdb-stream/3-querying-data.md
I closed the previous pull request to develop (#316) and opened one to `main` with the same changes.
=> Fixed JSON examples of "3-querying-data.md

firebase.json
Redirect hardware catalog to new location for that section
=> firebase: redirect hardware catalog pages

firebase.json, scripts/redirect_test/.gitignore, scripts/redirect_test/README.md, scripts/redirect_test/redirect_test.py
* Add script for testing redirects
* Create redirects for cloud sections of docs
=> 301 redirects

docusaurus.config.js
* Add help link to the Forum
* Clean up commented out code
=> footer: add forum and clean up

docs/data-routing/2-output-streams/9-event-types/README.md
Slug was interfering with correct link creation.
=> event-types: fix overview page slug

docs/getting-started/3-device-examples/2-compile-example-code/3-esp-idf/4-cloud-data.md, docs/getting-started/3-device-examples/2-compile-example-code/3-esp-idf/README.md, docs/partials-common/install-espidf.md, docs/partials-common/install-golioth-firmware-sdk.md
* Call out ESP-IDF in favor of ESP32
* Target tags when cloning repos
* Small code block syntax fix
=> Fix esp32 getting started

docs/firmware/golioth-firmware-sdk/firmware-upgrade/fw-update-zephyr.md, firebase.json
* Rename DFU sample to fw_update sample
* Use `CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION` in place of `CONFIG_GOLIOTH_SAMPLE_FW_VERSION`
=> firmware: OTA: rename DFU to fw_update

docs/firmware/golioth-firmware-sdk/README.md, docs/firmware/zephyr-device-sdk/README.md, docs/firmware/zephyr-device-sdk/_category_.yml, docs/landing_page.md
Move all references for Zephyr to lead to the Golioth Firmware SDK
=> Remove Beta

docs/landing_page.md
Fixes small typo of "field" in the landing page.
=> Fix typo in landing page

docs/data-routing/6-troubleshooting/README.md
Extremely minor and low-priority, can get merged in the next convenient release.
=> Correct typo in pipeline troubleshooting

docs/firmware/hardware/6-catalog/6-hardware-catalog.mdx, docs/getting-started/2-console/2-register.md, docusaurus.config.js, package-lock.json, package.json
- Remove the ideal-images plugin
- This was only being used in the Hardware Catalog
- It didn't work automatically, you had to import and use <Image params> components manually
- It blocked images from being imported normally, so it was also used in the FlexImage component I wrote because I had no other choice
- It blocked using the zoom image plugin
- Use the docusaurus-plugin-image-zoom to make images zoomable when clicked
=> Make images zoomable

package-lock.json, package.json
Upgrade Docusaurus and run `npm audit fix`.
=> upgrade to Docusuarus v3.4.0

docusaurus.config.js, package-lock.json, package.json
Adds a plugin for google tag manager.
=> Add google tag manager plugin

docs/data-routing/4-destinations/10-aws-s3.md
Adds documentation for the AWS S3 data destination.
=> Add aws-s3 data destination docs

docs/data-routing/4-destinations/10-aws-s3.md
Fixes a misspelling of "Services".
=> Fix typo in AWS S3 data destination

docs/data-routing/4-destinations/11-kafka.md
Adds documentation for Kafka data destination.
=> Add kafka data destination docs

docs/data-routing/3-transformers/7-base64.md
Adds documentation for the base64 pipelines transformer.
=> Add documentation for base64 transformer

docs/data-routing/3-transformers/8-embed-in-json.md
Adds documentation for the embed-in-json transformer.
=> Add embed-in-json transformer docs

docs/data-routing/4-destinations/4-webhook.md
Updates webhook data destination docs to disambiguate from webhook transformer.
=> Add disambiguation to webhook data destination docs

docs/data-routing/4-destinations/12-gcp-cloud-storage.md
Adds documentation for the GCP cloud storage data destination.
=> Add documentation for GCP cloud storage destination

docs/data-routing/5-examples/22-HERE-positioning.md, docs/data-routing/5-examples/23-google-geolocation.md
Adds a pipeline example for HERE's Positioning API.
Adds a Pipeline example for Google's Geolocation API.
=> Add location Pipeline examples

docs/data-routing/4-destinations/13-azure-blob-storage.md
Fixes incorrect table wrapping in parameters for azure-blob-storage.
=> destinations: fix azure-blob-storage table wrapping

docs/data-routing/5-examples/24-supabase.md
Fixes errors in supabase example pipelines.
=> pipelines: fix example supabase pipelines

.github/workflows/firebase-hosting-merge-develop.yml, .github/workflows/firebase-hosting-merge-main.yml, .github/workflows/firebase-hosting-pull-request.yml, package-lock.json, package.json
- Update Node.js version
- Update Node.js modules
=> Update to Docusaurus 3.7.0

docs/data-routing/4-destinations/14-lightdb-state.md
Adds docs for LightDB State data destination.
=> [pipelines/destination] add LightDB State data destination

docs/data-routing/3-transformers/9-webhook.md
Adds documentation for the new `embed` parameter.
=> [transformer/webhook] document `embed` parameter
