docs/getting-started/2-installing/2-packages.md

- Updated goliothctl and coap numbers
- Fixed typos

Fix: Update version numbers (closes #133), correct typos

---

docs/hardware/4-nrf91/2-quickstart/1-overview.md
docs/hardware/4-nrf91/2-quickstart/2-set-up-zephyr.md
docs/hardware/4-nrf91/2-quickstart/4-flash-sample.md
docs/partials/install-nrf91-sdk.md
docs/partials/install-zephyr-sdk-toolchain.md
docs/partials/setup-west-nrf91.md

- Removing `west patch` fixes #134 
- Adding SDK install steps fixes nRF91 build steps.

Remove west patch step, update SDK install instructions

---

docs/hardware/4-nrf91/2-quickstart/2-set-up-zephyr.md
docs/partials/install-nrf91-sdk.md

During west workspace setup we need to use newer version of NCS, as the
old version is not compatible with changes in SDK.
Update also how QCBOR is added as dependency to west.yml file (by
importing it from Golioth SDK manifest), so that its version does not
need to be specified explicitly.
Remove `west patch` step, as it was not required for long time and it
actually creates problems and confuses users.
Fixes: #134
Fixes: #131

nrf91: sync setup of west workspace with SDK

---

docs/cloud/1-services/5-ota/2-uploading-artifacts.md
docs/hardware/4-nrf91/2-quickstart/4-flash-sample.md
docs/partials/install-zephyr-sdk.md

As suggested by @ChrisGammell 
>should we be pointing people at the ssh logged in version of git repos?
>(the `west init`  line)
>installing on my new laptop and wasn't verified on github yet
>it might behoove us to either switch to the https version of the clone command or to mention people should have a login for github
The nRF sdk is already using an https remote instead of an ssh one:
https://github.com/golioth/docs/blob/eddd0e0b62930ba5422d19fd739bd8b26fe86894/docs/partials/install-nrf91-sdk.md?plain=1#L15

Use https as remote instead of ssh

---

docs/reference/5-websocket/3-Endpoints/1-lightdb.md
docs/reference/5-websocket/3-Endpoints/2-lightdb-stream.md
docs/reference/5-websocket/3-Endpoints/3-logging.md

PR opened to update the Reference/Websocket section to contain now how to filter the Logs and the LightDB streams.

docs: add documentation about the filters introduced in the Logs and LightDb Stream realtime endpoints

---

docs/partials/install-espressif-toolchain.md

Reported in #156, I found the placements of this to be a bit awkward. I think @vancefarren's suggestion to mention the output of the previous command is a good one. It makes the most sense to move this warning immediately after that `west espressif install` command. This commit also improves the content of the message.

improvement: better export path warning message and placement

---

docs/hardware/5-virtual-device/2-quickstart/3-simulating-devices-coap.md

The example uses a string, but the output was referring to reading a file.

fix: update coap example output

---

docs/cloud/2-output-streams/5-gcp-pubsub/1-overview.md

Change the presentation of the setup steps using headings so that they appear in the right sidebar table of contents: 
Made readability edits to the content.
A few images were moved above the bullet points that discuss them @miguel91it and @alvarowolfx will you look and make sure these setup steps are still well presented?

gcp-pubsub: edit content and change formatting

---

docs/reference/1-home.md
docs/reference/6-zephyr-sdk.md

It may take some time to integrate the Golioth Zephyr SDK Doxygen with our Docusaurus docs. This PR adds links to the Doxygen site so that its available to users until we have a chance for more through integration.
Edit: Here are the rendered pages for your convenience:
* [Reference section overview](https://golioth-docs-dev--pr171-szczys-link-to-doxyg-30bmggdh.web.app/reference)
* [Golioth Zephyr SDK page](https://golioth-docs-dev--pr171-szczys-link-to-doxyg-30bmggdh.web.app/reference/golioth-zephyr-sdk)

add: reference link and page for Zephry SDK Doxygen

---

docs/hardware/assets/hardware-catalog.css
scripts/device-catalog/index.js
scripts/device-catalog/support.json

- Submenu list name update: Quickstart -> Verified + Quickstart
- Root folder name update: 6-boards -> 6-catalog
- Fixed CSS that hides "unverified" menu that stopped working after moving
- Other fixes to make the script match new Device catalog category
- Root: Hardware Catalog -> Sub-menu: Hardware Catalog Search
To test we just need to run the local project as we normally would, and then run the script that generates the Device Catalog.
`npm run build-device-catalog`
And then test if everything match if the live/expected version with the latest zephyr boards.

Updating device catalog script to match new docs/links structure

---

docs/hardware/5-virtual-device/2-quickstart/5-simulating-devices-qemu.md
docs/partials/install-qemu-sdk.md

Fixes for things I observed when going through the Virtual Devices guide: https://docs.golioth.io/hardware/virtual-device/quickstart/qemu-install/
* Added libglib2.0-dev to apt install list to prevent the following error on Ubuntu 20.04: `fatal error: glib.h: No such file or directory`
* The snippet to install `west` was missing from Qemu setup page

qemu: fix missing apt install, missing west install

---

docs/partials/check-toolchain.md
docs/partials/install-zephyr-sdk-toolchain.md
docs/partials/setup-west-nrf91.md

- Following this [task](https://golioth.atlassian.net/browse/GWP-173?atlOrigin=eyJpIjoiNDE1NGEyNjVlMDczNDY0NTk5YzhhMTFhYmJjYmI2YzYiLCJwIjoiaiJ9), I updated all `groupId`s on the Tabs components. Now its possible to have to same selected OS selected across all pages, keeping its state even after refreshing the page.
- Also, I updated some items that were showing `Ubuntu` into `Linux` to keep consistency with majority of the other pages.
- Please let me know if this is not the expected behavior
- Select the OS that you want at any page, and then change/refresh the page to see if it's keeping its state

fix: update os tab selector to allow keep state across all pages

---

docs/hardware/4-nrf91/2-quickstart/2-set-up-zephyr.md
docs/hardware/4-nrf91/2-quickstart/3-hardware-programmer.md
docs/hardware/4-nrf91/2-quickstart/5-flash-sample.md
docs/partials/install-nrf91-sdk.md
docs/partials/nrf9160-bootloader-flashing.md

* Change directions to use west-ncs.yml manifest install method
* Change all nRF-based directory mentions from zephyr-nrf to golioth-ncs-sdk

New NCS install method

---

docs/hardware/3-esp32/2-quickstart/2-set-up-zephyr.md
docs/hardware/3-esp32/2-quickstart/3-flash-sample.md
docs/hardware/5-virtual-device/2-quickstart/5-simulating-devices-qemu.md
docs/partials/install-zephyr-sdk-unix.md
docs/partials/install-zephyr-sdk-windows.md
docs/partials/setup-zephyr-unix.md
docs/partials/setup-zephyr-windows.md

* Use west-zephyr.yml instead of west.yml
* Use golioth-zephyr-workspace as the install directory

change: new install method for Golioth Zephry SDK

---

docs/hardware/3-esp32/2-quickstart/2-set-up-zephyr.md
docs/partials/install-espressif-toolchain-unix.md
docs/partials/install-espressif-toolchain-windows.md
docs/partials/install-zephyr-sdk-toolchain.md

Updates to docs still needed for MacOS and Windows

fix: update Linux zephyr-sdk install for 0.14.1

---

docs/partials/install-espressif-toolchain.md
docs/partials/install-zephyr-sdk-toolchain.md
docs/partials/install-zephyr-sdk.md
docs/partials/setup-zephyr.md

When using this repo as a submodle for other documentation, we
need relative import paths to help avoid breaking the docusaurus
build.

refactor: use relative paths for imports

---

docs/partials/setup-zephyr-windows.md
docs/partials/setup-zephyr.md

* Chocolatey installs Python3 so we don't need a separate step
* The `python` command defaults to Python3 (show how to check)
* Remove prompt from powershell commands based on user feedback

Windows install: update for better workflow

---

docs/partials/install-tools.mdx

We internally upgraded the coap and goliothctl command line tools to support ARM Windows and ARM/M1 Macs. This PR add links to download the pre build binaries.

feat: add arm windows and mac binaries links

---

docs/partials/install-espressif-toolchain-unix.md
docs/partials/install-espressif-toolchain-windows.md

Miguel ran into an error when following the ESP32 Zephyr
Quickstart instructions, on the step where espressif submodules
are updated and installed:
west espressif update
usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: ...
This happened because he was in ~/zephyr-sdk-0.14.2 when
he tried to run the command.
The instructions should direct the user to change to the
SDK directory before running the west espressif commands.
Signed-off-by: Nick Miller <nick@golioth.io>

espressif-install: run from inside SDK

---

docs/partials/install-espressif-toolchain-unix.md
docs/partials/install-espressif-toolchain-windows.md

Users have not needed to set env vars for ESP32 since May 14. Removed
this warning as it is no longer likely to be useful.

Remove warning about ESP32 env variable

---

docs/cloud/1-services/4-lightdb-stream/3-querying-data.md
docs/cloud/1-services/4-lightdb-stream/README.md
docs/firmware/firmware-client-auth.drawio.svg
docs/getting-started/2-console/1-overview.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_device_list.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_lightdb.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_lightdb_delete.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_lightdb_get.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_lightdb_listen.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_lightdb_set.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_stream.md
docs/reference/5-command-line-tools/1-goliothctl/goliothctl_stream_query.md

Following commands were executed in root directory:
```
$ sed -i 's/Light DB/LightDB/g' `find -type f`
$ sed -i 's/LightDB stream/LightDB Stream/g' `find -type f`
$ sed -i 's/LightDB Streams/LightDB Stream/g' `find -type f 
```
with some manual adjustments.

treewide: fix 'LightDB' and 'LightDB Stream' spelling

---

scripts/device-catalog/support.json

Fix: missed name change for QEMU level

---

docs/hardware/2-esp32/2-zephyr-quickstart/2-set-up-zephyr.md
docs/partials/install-espressif-toolchain-unix.md
docs/partials/install-espressif-toolchain-windows.md
docs/partials/install-zephyr-sdk-toolchain.md

Update download links and instructions for Zephyr SDK 0.15.0 Change west espressif update/install to west blob command

Update Zephyr SDK to v0.15.0

---

docs/hardware/2-esp32/2-zephyr-quickstart/2-set-up-zephyr.md
docs/hardware/3-mimxrt1060_evkb/1-zephyr-quickstart/2-set-up-zephyr.md
docs/partials/sample-build.mdx

Abstract the sample build section of Setup Zephyr pages so it can be reused with a different board name as a property of the import.

hardware: fix board name in sample build code

---

docs/partials/espidf/install-espidf.md

Fixes the following warnings:
Component SetupZephyrUnix was not imported, exported, or provided by MDXProvider as global scope

esp-idf install: remove erroneous import

---

docs/reference/2-protocols/2-mqtt/3-lightdb.md
docs/reference/2-protocols/2-mqtt/4-lightdb-stream.md
docs/reference/2-protocols/2-mqtt/5-logging.md
docs/reference/2-protocols/2-mqtt/6-ota.md

MQTT topics do not typically begin with a `/`, even if it is a [common misunderstanding](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/):
> ### Never use a leading forward slash
>
> A leading forward slash is permitted in MQTT. For example, `/myhome/groundfloor/livingroom`. However, the leading forward slash introduces an unnecessary topic level with a zero character at the front. The zero does not provide any benefit and often leads to confusion.
I verified that your implementation just trims the leading slash under the hood, so it sounds best to just not recommend using it.

MQTT: topic paths do not begin with a /

---

docs/hardware/2-esp32/2-zephyr-quickstart/3-flash-sample.md

Fix: symbol name for WiFi psk

---

docs/reference/2-protocols/2-mqtt/4-lightdb-stream.md

MQTT Stream implementation is write-only. This commit removes the mention of an endpoint to subscribe to a stream.

Remove MQTT Stream sub example

---

docs/hardware/2-esp32/1-espidf-quickstart/2-set-up-espidf.md
docs/hardware/2-esp32/1-espidf-quickstart/3-flash-sample.md
docs/hardware/2-esp32/1-espidf-quickstart/README.md
docs/partials/espidf/install-golioth-firmware-sdk.md
docs/reference/1-home.md
docs/reference/6-device-sdks/1-esp-idf-sdk.md
docs/reference/6-device-sdks/1-firmware-sdk.md

The intent is to direct ESP-IDF users to the cross-platform firmware SDK. The prior golioth-esp-idf-sdk repo is being deprecated.
Signed-off-by: Nick Miller <nick@golioth.io>

replace golioth-esp-idf-sdk with golioth-firmware-sdk

---

docs/reference/2-protocols/1-coap/7-limits.md

Generalizes name to CoAP LImits and adds section about payload length.

coap limitations: rename page, add payload limit

---

docs/hardware/5-virtual-device/2-zephyr-quickstart/5-simulating-devices-qemu.md

Update the build command to use the qemu_x68 target used in all of the Golioth samples.
This fixes the issues the @ilaue-prospr reported in #247. The Golioth Zephyr SDK targets qemu_x86 so the docs should target that as well.

simulating-devices: update qemu build command

---

docs/cloud/1-services/5-ota/2-uploading-artifacts.md

Fixes a small typo where "them" was used instead of "then".
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Fix small typo in OTA uploading artifacts docs

---

docs/hardware/2-esp32/1-espidf-quickstart/4-ota.md

While going through the [ESP-IDF Quickstart](https://docs.golioth.io/hardware/esp32/espidf-quickstart/), I noticed an inconsistency between the docs and the latest version of [golioth-firmware-sdk](https://github.com/golioth/golioth-firmware-sdk). Looks like these changes haven't been included in a release yet, but the quickstart instructions don't checkout to a specific version of the SDK so I continued by using the tip of `main`.
Looks like the logger tags set with `#define TAG "<tag name>"` were recently updated to use the macro `LOG_TAG_DEFINE(<tag name>` instead.
I did end up getting the ESP32 connected and I completed an OTA, very cool! :rocket:

Update ESP-IDF Quickstart log tag line to match latest example

---

docs/reference/2-protocols/1-coap/6-ota.md

Adds a note specifying that the desired release version will be the most recently created release that is enabled.

feat: add note defining desired release version

---

docs/reference/5-command-line-tools/1-goliothctl/goliothctl_apikeys_create.md

PR related to the [GB-602: Add "name -> TAGs" field to API keys](https://golioth.atlassian.net/browse/GB-602).
Adding reference to tagging apikeys through the `goliothctl apikeys create` command.

Add reference for tagging apikeys

---

docs/cloud/1-services/4-lightdb-stream/2-sending-data.md

Updates the LightDB Stream POST description to assert that only devices can write to LightDB Stream and that they do so over CoAP.

fix: Update LightDB Stream POST description

---

docs/reference/3-rest-api/2-auth.md
docs/reference/4-websocket/2-auth.md

Using `X-API-Key` in a query will cause authentication to fail. This should be all lowercase: `x-api-key`

fix: use lowercase for x-api-key

---

docs/firmware/golioth-firmware-sdk/light-db-state/README.md

Correct double mention of "State" to differentiate between Stream and State

firmware: state: fix note in summary page

---

docs/getting-started/2-console/5-choose-device.md
docs/hardware/1-home.md
docs/partials-common/getting-started_choose-device.md

add a matrix of hardware vendors that outlines Golioth SDK support and links to quickstart guides.

hardware overview: add 'Start Here' section

---

docs/hardware/1-home.md

* Add section for beta platform support
* Link to the getting started information for the Zephry port of the Golioth Firmware SDK

hardware: add zephyr beta quickstart

---

docs/firmware/zephyr-device-sdk/authentication/certificate-auth.md

When creating device certificates, the unique identifier will be assigned to the device name by Golioth servers, not the unique hardware id.

firware: cert auth: use device name

---

docs/firmware/golioth-firmware-sdk/authentication/certificate-auth.md

The hint text in the device cert generation script incorrectly referenced a unique hardware id. This updates the text to reference a unique device name.

firmware: certs: update hint text for device name

---

docs/firmware/golioth-firmware-sdk/authentication/certificate-auth.md

Updates reference to Zephyr SDK to instead mention Firmware SDK.

firmware: auth: update reference to Firmware SDK

---

docs/getting-started/1-overview.md

Add Sign Up hyperlink to the Getting Started section as [suggested by a user in the forum](https://forum.golioth.io/t/small-improvement-for-getting-started/374).

Add sign up hyperlink to Getting Started

---

docs/partials-common/install-zephyr-sdk-toolchain.md

Use most recent version of the Zephyr SDK toolchain.

update Zephyr SDK install instructions

---

docs/landing_page.md

When merging multiple PRs this link did not get updated to the new data-handling location.
This should fix the issue that cause the bad deploy: https://github.com/golioth/docs/actions/runs/7012998907

landing-page: fix link to data-handling

---

docusaurus.config.js
src/css/custom-swagger-ui.css
src/css/custom.css

Swagger CSS has been broken, especially in dark mode. This PR fixes the style and closes #253

Fix swagger css

---

firebase.json

When the previous commit was merged it included a redirect for dev but not for prod. This commit adds the prod redirect, and ensures that URLs with and without a trailing slash will both be redirected correctly.

add tiers redirect to production

---

.github/workflows/firebase-hosting-merge-develop.yml

Add robot.txt when docs.golioth.dev is deployed so that search engines will not index the preview site.
I [tested this initially](https://github.com/golioth/docs/actions/runs/7023432503/job/19109924005#step:6:5) and found the file to be added correctly:
```
Run cat build/robots.txt
User-agent: *
Disallow: /
```

workflow: add robots.txt to dev deploy

---

docusaurus.config.js

Docusaurus includes a blog by default. We have been hosting a "Hello World" at /blog and this commit removes that page and all /tags pages.

disable blog:

---

src/css/custom.css

Chevrons for the navigation sidebar were showing up as white on white in light mode.

css: fix lightmode navigation chevrons

---

docs/_partials-common/ncs-install-golioth-firmware-sdk-for-unix.md
docs/_partials-common/ncs-install-golioth-firmware-sdk-for-windows.md
docs/_partials-common/zephyr-install-golioth-firmware-sdk-for-unix.md

Update installation commands to use the Golioth Firwmare SDK.
The Zephyr/NCS quickstarts used `west init` repository paths for the Golioth Zephyr SDK when they should have been using the Zephyr support in the Golioth Firmware SDK
Resolves #338

getting-started: zephyr: fix repository URL

---

docs/_partials-common/deprecation-warning-zephyr-sdk.md
docs/firmware/zephyr-device-sdk/README.md
docs/firmware/zephyr-device-sdk/authentication/README.md
docs/firmware/zephyr-device-sdk/authentication/certificate-auth.md
docs/firmware/zephyr-device-sdk/authentication/psk-auth.md
docs/firmware/zephyr-device-sdk/device-settings-service.md
docs/firmware/zephyr-device-sdk/firmware-upgrade/2-build-sample-application.md
docs/firmware/zephyr-device-sdk/firmware-upgrade/4-watch-device-update.md
docs/firmware/zephyr-device-sdk/firmware-upgrade/5-dfu-sample-guide.md
docs/firmware/zephyr-device-sdk/firmware-upgrade/README.md
docs/firmware/zephyr-device-sdk/golioth-client.md
docs/firmware/zephyr-device-sdk/light-db-stream/README.md
docs/firmware/zephyr-device-sdk/light-db-stream/guide-lightdb-stream.md
docs/firmware/zephyr-device-sdk/light-db/README.md
docs/firmware/zephyr-device-sdk/light-db/guide-light-db-observe.md
docs/firmware/zephyr-device-sdk/light-db/guide-lightdb-get.md
docs/firmware/zephyr-device-sdk/light-db/guide-lightdb-set.md
docs/firmware/zephyr-device-sdk/logging/README.md
docs/firmware/zephyr-device-sdk/logging/guide-logging.md
docs/firmware/zephyr-device-sdk/migration_guide.md
docs/firmware/zephyr-device-sdk/remote-procedure-call.md
docs/firmware/zephyr-device-sdk/zephyr-app.md

* [Migration Guide: add link and sidebar entry](https://github.com/golioth/docs/commit/4484d7358d22452db21ea77ad7858c256dcb9868)
* [add deprecation to all Golioth Zephyr SDK pages](https://github.com/golioth/docs/commit/3cf876c3ad7985ed0f61bc7659d897c493e1ff8e)

add Golioth Zephyr SDK deprecation notice to point to Golioth Firmware SDK

---

docs/_partials-common/ncs-install-golioth-firmware-sdk-for-unix.md
docs/_partials-common/ncs-install-golioth-firmware-sdk-for-windows.md
docs/_partials-common/zephyr-install-golioth-firmware-sdk-for-unix.md
docs/_partials-common/zephyr-install-golioth-firmware-sdk-for-windows.md

When installing a Golioth workspace for Zephyr/NCS you must change into the SDK directory before running submodule init.

getting started: fix directory change

---

docs/reference/2-protocols/2-device-auth.md

Adds links to the firmware SDK documentation that details how to use PSKs and Certificates with the SDK on devices.

Add links to firmware SDK docs from device auth reference

---

docs/firmware/zephyr-device-sdk/logging/README.md

Fixes a broken link to logging service in Zephyr SDK documentation.

Fix broken link to logging service

---

docs/reference/2-protocols/1-coap/4-lightdb-stream.md

Removes the reference to the GET endpoint to LightDB Stream, which is no longer supported.

Remove reference to unsupported LightDB Stream device GET endpoint

---

docs/reference/2-protocols/1-coap/7-ota.md

The reason code section previously referenced state codes by mistake.

reference: coap: ota: correctly reference reason codes

---

docs/data-routing/2-output-streams/1-mongo/README.md
docs/data-routing/2-output-streams/8-influx/README.md

Updates the mongo and influx outputstream docs examples to correctly reflect the format of data sent to each destination.

Update mongo and influx outputstream docs to correctly reflect format

---

docs/landing_page.md

Title currently says "What is Golioth?" which is awkward when shown on a browser tab. This change update to "Golioth Docs".
resolves https://github.com/golioth/devrel-issue-tracker/issues/390

landing page: update title

---

docs/firmware/zephyr-device-sdk/light-db-stream/guide-lightdb-stream.md

Add note to the LightDB Stream section of the deprecated Golioth Zephyr SDK docs indicating that a pipeline is needed to send streaming data to Golioth.
resolves https://github.com/golioth/firmware-issue-tracker/issues/523

zephyr SDK: stream: add admonition about pipelines

---

firebase.json

Updates redirects for new data routing structure and changes priority order such that more specific rules come before less specific ones.
From [Firebase docs](https://firebase.google.com/docs/hosting/full-config#redirects):
> Important: Within the redirects attribute, Hosting applies the redirect defined by the first rule with a URL pattern that matches the requested path. So, you need to deliberately order the rules within the redirects attribute.

Update redirects and change priority order

---

docs/data-routing/5-examples/11-zapier-webhook.md

Adds example integrating with Zapier using Webhooks and Zapier's Webhooks by Zapier app. It doesn't rely on a "native" Zapier integration.
Signed-off-by: Jonathan Beri <jberi@golioth.io>

Zapier Webhook Example

---

src/components/usethispipeline.js
src/theme/CodeBlock/Content/Element.js
src/theme/CodeBlock/Content/String.js
src/theme/CodeBlock/Content/styles.module.css

This customizes the CodeBlock title pane to show the "Use this pipeline" button floated right of the title for desktop view and below the title (float left) for mobile view.
The CodeBlock/Content component needed to be swizzled to make this change. This may call for updates if the CodeBlock component has upstream changes in future updates.

Show "Use this pipeline" button in title pane of code block

---

docs/data-routing/5-examples/12-pipedream-webhook.md

Example for Pipedream using HTTP / Webhook app.  It doesn't rely on a "native" Pipedream integration.
Signed-off-by: Jonathan Beri <jberi@golioth.io>

Pipedream Webhook example

---

docs/data-routing/5-examples/13-n8n-webhook.md

Example for n8n using Webhook node. It doesn't rely on a "native" n8n integration.
Signed-off-by: Jonathan Beri <jberi@golioth.io>

n8n Pipeline example

---

docs/getting-started/2-console/3-manage-devices.md

Two pages of the getting started guide are imported in the Developer Training to walk people through the console registration process. When linking to other pages, use the full URL (https://docs.golioth.io/etc) to ensure pages don't have broken links when imported outside of this repo.

getting started: use full URL in manage devices page

---

docs/data-routing/3-transformers/5-json-patch.md
docs/data-routing/5-examples/14-conditional-json-patch.md

Adds documentation for the json-patch transformer.
Adds an example demonstrating how a JSON patch could be conditionally applied
based on device ID.

Add docs and example for `json-patch` transformer

---

docs/data-routing/4-destinations/9-memfault.md
docs/data-routing/5-examples/15-memfault.md

Adds documentation for the memfault data destination.
Adds an example pipeline for the memfault data destination.

Add memfault data destination documentation and example

---

docs/data-routing/5-examples/16-slack-webhook.md

Adds an example for a pipeline that delivers messages to a Slack incoming webhook.

Add example for slack webhook pipeline

---

docs/data-routing/3-transformers/9-webhook.md
docs/data-routing/4-destinations/1-lightdb-stream.md
docs/data-routing/4-destinations/10-aws-s3.md
docs/data-routing/4-destinations/11-kafka.md
docs/data-routing/4-destinations/2-mongodb.md
docs/data-routing/4-destinations/3-influxdb.md
docs/data-routing/4-destinations/4-webhook.md
docs/data-routing/4-destinations/5-azure-event-hubs.md
docs/data-routing/4-destinations/6-aws-sqs.md
docs/data-routing/4-destinations/7-gcp-pubsub.md
docs/data-routing/4-destinations/9-memfault.md
docs/data-routing/4-destinations/README.md

Adds documentation for the webhook transformer.
Not every destination incures usage, so we opt to be more specific by denoting
those that do on their individual docs pages rather than the top level
destinations page.

Add webhook transformer documentation

---

docs/data-routing/4-destinations/13-azure-blob-storage.md

Adds documentation for the Azure Blob Storage data destination.

Add documentation for Azure Blob Storage destination

---

docs/data-routing/3-transformers/6-struct-to-json.md

The example YAML used `length` where it should have used `lengthField`

data-routing: transformers: struct-to-json: fix example yaml

---

docs/reference/1-home.md
docs/reference/5-device-sdks/2-zephyr-sdk.md
docs/reference/5-device-sdks/_category_.yml
docs/reference/5-golioth-firmware-sdk.md
firebase.json

This PR places the Golioth Firmware SDK reference page as a top-level entry in the References section. We continue to host this placeholder page that points to the external doxygen as future plans will incorporate the doxygen into the main docs site.
- Remove references to the deprecated Golioth Zephyr SDK.
- Replace "Device SDKs" category the Golioth Firmware SDK page.

reference: remove deprecated SDK and replace category page

---

docs/firmware/golioth-firmware-sdk/firmware-upgrade/fw-update-zephyr.md
docs/getting-started/3-device-examples/2-compile-example-code/1-zephyr/02-zephyr-samples.md
docs/getting-started/3-device-examples/2-compile-example-code/2-zephyr-ncs/02-zephyr-samples.md

Change board names to use forward slash instead of underscore to match new device model for Zephyr v3.7.0.
This should not be merged until Golioth Firmware SDK v0.15.0 is released.
resolves https://github.com/golioth/firmware-issue-tracker/issues/618

Update for zephyr 3.7

---

docs/_partials-common/build-fw-nrf91.md
docs/firmware/golioth-firmware-sdk/firmware-upgrade/fw-update-zephyr.md

Using sysbuild is now recommended with new NCS versions, as the old multi-image
build system got deprecated. The resulting application upgrade
file (app_update.bin) is still the same as in old NCS.

docs: firmware: use --sysbuild for nrf9160dk fw_update builds

---

docs/getting-started/3-device-examples/1-precompiled-binaries/thingy91.md

Update the name of the thingy91 binary to match what is automatically generated when a new release of the firmware is created.
Resolves https://github.com/golioth/devrel-issue-tracker/issues/515

getting-stared: thingy91: fix binary name

---

docs/reference/3-management-api/1-auth.md

Updates the API key documentation to reflect the current use of API keys on golioth and provide more information about their scope and lifetime.

[reference] update API key documentation to reflect current state

---

docs/reference/4-command-line-tools/1-goliothctl/goliothctl_apikeys_create.md

Update the `goliothctl` reference page to show only the basic APIKEY type type that is currently supported by Golioth.

reference: update goliothctl for current state of APIKEY

---

docs/data-routing/5-examples/25-edge-impulse.md

Add information on how the Golioth Edge Impulse Demo uses Pipelines to stream classification data to LightDB Stream, and raw accelerometer data to Amazon S3.
Preview generated by this PR: https://golioth-docs-dev--pr449-szczys-edge-impulse-l0tkxyl5.web.app/data-routing/examples/edge-impulse
Resolves https://github.com/golioth/devrel-issue-tracker/issues/534

data-routing: add Edge Impulse example

---

docs/application-services/3-location/2-resolving-location.md
docs/application-services/3-location/3-querying-data.md
docs/application-services/3-location/README.md
docs/application-services/3-location/_category_.yml
docs/reference/2-device-api/3-api-docs/8-location.md

Adds initial documentation for the Golioth Location service.

[location] Add initial Golioth Location documentation

---

docs/application-services/3-location/2-resolving.md
docs/application-services/3-location/3-querying.md
docs/application-services/3-location/README.md
docs/reference/2-device-api/3-api-docs/8-location.md

Fixes the path structure for location service docs to use file names rather than id.

[location] location service docs path updates

---

docs/application-services/1-lightdb-state/3-read-write-data.md

Fixes typos in the LightDB State read / write documentation.

application services: state: fix typos

---

docs/firmware/hardware/5-virtual-devices/2-zephyr-quickstart/5-simulating-devices-qemu.md
docs/getting-started/3-device-examples/2-compile-example-code/1-zephyr/01-set-up-zephyr.md
docs/getting-started/3-device-examples/2-compile-example-code/2-zephyr-ncs/01-set-up-ncs.md

If the workspace directory param is not specified when calling the partial, the workspace directory will render as `undefined`.
Headings in tabs being rendered multiple times. Limit ToC heading depth for these pages.

Specify directory for virtual devices workspace; Fix ToC for zephyr install pages

---

docs/data-routing/4-destinations/9-memfault.md

Adds docuemntation for specifying an alternate ID source to be used for device serial number.

[destination/memfault] add alternate ID support

---

docs/firmware/golioth-firmware-sdk/device-settings-service.md

Fixes broken link to firmware SDK examples.

settings: fix link to firmware SDK examples

---

docs/_partials-common/login-flow.md

Updates the authentication CLI tutorial section to show API key login as an option.

goliothctl: add tutorial section on apikey login
